version: 2.1

orbs:
  heroku: circleci/heroku@1.2.2
  coveralls: coveralls/coveralls@1.0.6
  sonarcloud: sonarsource/sonarcloud@1.0.2

jobs:
  build-test:
    working_directory: ~/titanic
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run:
          name: Linting
          command: npm run lint
      - run:
          name: Testing
          command: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      - run:
          name: Security Audit
          command: npm run package-audit
      - sonarcloud/scan
      - coveralls/upload:
          verbose: true
          path_to_lcov: "coverage/*/lcov.info"
  deploy-develop:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git
  deploy-prod:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - run: 
          name: Build for Production
          command: npm build --prod # this wont work
      - heroku/deploy-via-git


workflows:
  test-deploy:
    jobs:
      - build-test:
          context: SonarCloud  
      - deploy-develop:
          requires:
            - build-test
          filters:
            branches:
              only:
                - develop
      - deploy-prod:
          requires:
            - build-test
          filters:
            branches:
              only:
                - master
            