version: 2.1

jobs:
  build-test:  # If more build steps are required, add them here
    docker:
      - image: circleci/node:10.19.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Install Angular
          command: npm install -g @angular/cli
      - run:
          name: Validate Angular
          command: ng v
workflows:
  static-testing:
    jobs:
      - build-test